### ISSUE TITLE
Slack Form Change

### ISSUE THREAD

**Issue by Joe0** [juanrgon/slack-emoji-uploader#3]
Slack changed the way the UI adds an emoji. Users are getting the following error:
![Error Message](https://i.imgur.com/cxnHKcs.png)

Instead of using crumb, they have a token (boot_data.api_token) and send that. Also, the form id no longer exists, along with some other changes.

**Comment by juanrgon** [comment]
Thanks for the heads up! I should have a fix out soon

**Comment by Boosik** [comment]
Hi @juanrgon 
Any updates? I love this addon and it's sad that it's broken right now. 😢

**Comment by cpchen** [comment]
Any update? :)

**Comment by hfrsoussama** [comment]
Still waiting for a fix :/

**Comment by juanrgon** [comment]
The latest version of the app has resolved this 🎉
